### ISSUE TITLE
Add Tokio ecossystem support

### ISSUE THREAD

**Issue by luisholanda** [Unleash/unleash-client-rust#30]
### Describe the feature request

Give the user the option to use a tokio-based HTTP stack.

### Background

At $DAILY_JOB, our Rust codebase is 100% tokio-based, using the `unleash-api-client` crate as dependency added 100+ crates to our `Cargo.lock`, which is _bad_.

Checking the added dependencies, many of them are crates of the `async-std` ecossystem, which we would not need to pull if we had the option to use a tokio-based HTTP stack.

### Solution suggestions

We could gate both the async-std and a tokio-based http (e.g. hyper) implementations behind cargo features (keeping the async-std enabled by default).

From what I understood of the implementation, the only method that does HTTP calls is `Client::poll_for_updates` (edit: `Client::register` also does a HTTP call). If so, we would to change the code to something like:

```rust
impl Client<F> {
	pub async fn poll_for_updates(&self) {
		#[cfg(feature = "async-std")]
		self.poll_for_updates_async_std().await;
		#[cfg(feature = "tokio")]
		self.poll_for_updates_tokio().await;
	}

	#[cfg(feature = "async-std")]
	async fn poll_for_updates_async_std(&self) {
		... // current implementation
	}
	
	#[cfg(feature = "tokio")]
	async fn poll_for_updates_tokio(&self) {
		...
	}
}
```

I'm open to work on fixing this issue.

**Comment by luisholanda** [comment]
Another option would be to give the user the option to provide their on HTTP implementation, which would remove the need to depend on an async-runtime.

**Comment by luisholanda** [comment]
My current opinion is that the best approach were would be to make the `http` field in `Client` generic and bounded by a trait `UnleashApi`. This crate then could keep exposing the `surf`-based implementation of the trait (that is enabled based on a cargo feature).

At first, I though that a simple switch of implementation based on feature would suffice, but users may have special needs that the default implementation wouldn't support (e.g. at our codebase, we only use rustls for TLS, we don't have openssl as transitive dependency). However, having a trait that the user can fully implement give them more flexibility (a specific user-case that came in my mind now are temporary authorization tokens when implementing custom authorization, which right now would require re-creating the client when the token changes).

**Comment by FredrikOseberg** [comment]
Thanks @luisholanda. I'll bring this up with the team today, will get back to you shortly.

**Comment by FredrikOseberg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issue: Rust client dependencies](https://trello.com/c/OpGm1U7D/1140-github-issue-rust-client-dependencies)

**Comment by sighphyre** [comment]
Hi @luisholanda, thanks for the inputs here. I can very much see how pulling in a ton of dependencies that you neither want nor need is problematic. I like the suggestion you make about allowing the possibility to provide a custom HTTP client implementation, it sounds like between that and gating the async runtime that would solve your problems while making minimal adjustments to the way the sdk works at the moment. If you'd be willing to do a spike on this, I would love to take a look! Would also be great to @rbtcollins inputs on this too

**Comment by rbtcollins** [comment]
I think bring your own would be a bit enthusiastic right off the bat, let's treat that as a separate feature.

I have no issue just migrating to tokio, surf was arbitrary... as long as what we move too has no hard dependency on the runtime (since that would make us unusable for async-std or smol). Surf today has that property of no runtime dependency.

If there are no such clients in the Tokio ecosystem, then yes, features for each and surf as default.

**Comment by luisholanda** [comment]
> I have no issue just migrating to tokio, surf was arbitrary... as long as what we move too has no hard dependency on the runtime 

Ok! I'll do some experiments today to see if I find something that we can use without having to create a bunch of features.

> If you'd be willing to do a spike on this, I would love to take a look!

I'll see if I can do a prototype later this week.

**Comment by luisholanda** [comment]
I didn't find a HTTP implementation that would solve the dependencies problem for all runtimes, so I decided to go with implementing separated features in #31.

**Comment by rbtcollins** [comment]
This should be resolved for you, in main at least.
